[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
extism-pdk = { version = "1.0.0-rc1", path = "../../extism-pdk" }
proto_pdk = { version = "0.13.0", path = "../../proto/crates/pdk" }
proto_pdk_api = { version = "0.13.0", path = "../../proto/crates/pdk-api" }
proto_pdk_test_utils = { version = "0.15.1", path = "../../proto/crates/pdk-test-utils" }
regex = { version = "1.10.2", default-features = false, features = [
	"std",
	"unicode",
] }
serde = "1.0.195"
serde_json = "1.0.111"
starbase_sandbox = "0.1.12"
tokio = { version = "1.35.1", features = ["full"] }

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = "s"
panic = "abort"
