[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
extism-pdk = "0.3.4"
proto_pdk = { version = "0.8.1" }            # , path = "../../proto/crates/pdk" }
proto_pdk_api = { version = "0.8.1" }        # , path = "../../proto/crates/pdk-api" }
proto_pdk_test_utils = { version = "0.8.4" } # , path = "../../proto/crates/pdk-test-utils" }
serde = "1.0.189"
serde_json = "1.0.107"
starbase_sandbox = "0.1.11"
tokio = "1.33.0"

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = "s"
panic = "abort"
