[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
extism-pdk = "0.3.4"
proto_pdk = { version = "0.10.3" } # , path = "../../proto/crates/pdk" }
proto_pdk_api = { version = "0.10.4" } # , path = "../../proto/crates/pdk-api" }
proto_pdk_test_utils = { version = "0.11.1" } # , path = "../../proto/crates/pdk-test-utils" }
regex = { version = "1.10.2", default-features = false, features = [
	"std",
	"unicode",
] }
serde = "1.0.193"
serde_json = "1.0.108"
starbase_sandbox = "0.1.12"
tokio = { version = "1.34.0", features = ["full"] }

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = "s"
panic = "abort"
