[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
extism-pdk = "0.3.4"
proto_pdk = { version = "0.6.5" }            # , path = "../../proto/crates/pdk" }
proto_pdk_api = { version = "0.6.3" }        # , path = "../../proto/crates/pdk-api" }
proto_pdk_test_utils = { version = "0.5.9" } # , path = "../../proto/crates/pdk-test-utils" }
serde = "1.0.188"
serde_json = "1.0.105"
starbase_sandbox = "0.1.8"
tokio = "1.32.0"
