[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
extism-pdk = "0.3.3"
# proto_pdk = { version = "0.4.1", path = "../proto/crates/pdk" }
# proto_pdk_test_utils = { version = "0.3.3", path = "../proto/crates/pdk-test-utils" }
proto_pdk = "0.4.1"
proto_pdk_test_utils = "0.3.3"
serde = "1.0.183"
starbase_sandbox = "0.1.8"
tokio = "1.29.1"
