[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
extism-pdk = "0.3.3"
proto_core = "0.12.2"
proto_pdk = { version = "0.2.3" } # , path = "../proto/crates/pdk" }
proto_pdk_test_utils = "0.1.3"
serde = "1.0.167"
starbase_sandbox = "0.1.5"
tokio = "1.29.1"
