[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
extism-pdk = "0.3.3"
proto_core = { version = "0.13.0", path = "../proto/crates/core" }
proto_pdk = { version = "0.3.0", path = "../proto/crates/pdk" }
proto_pdk_test_utils = { version = "0.2.0", path = "../proto/crates/pdk-test-utils" }
serde = "1.0.167"
starbase_sandbox = "0.1.5"
tokio = "1.29.1"
