[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
extism-pdk = { version = "1.1.0" }
nodejs_package_json = "0.2.0"
proto_pdk = { version = "0.17.5" } #, path = "../../proto/crates/pdk" }
proto_pdk_api = { version = "0.17.3" } #, path = "../../proto/crates/pdk-api" }
proto_pdk_test_utils = { version = "0.20.1" } #, path = "../../proto/crates/pdk-test-utils" }
regex = { version = "1.10.3", default-features = false, features = [
	"std",
	"unicode",
] }
serde = "1.0.197"
serde_json = "1.0.114"
starbase_sandbox = "0.5.0"
tokio = { version = "1.36.0", features = ["full"] }

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = "s"
panic = "abort"
