name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v[0-9]+*"
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
        with:
          cache: false
          targets: wasm32-wasi
      - uses: moonrepo/build-proto-plugin@v0
